### ISSUE TITLE
conversion of (filtrations of) simplicial complex(es) to directed complexes

### ISSUE THREAD

**Issue by vitskov** [nebneuron/Simplicial#12]
vertices of directed complexes have fixed type: Array{Int16,1}

conversion is a pain, since currently simplicial complexes and combinatorial codes are created with arbitrary type. 

Needed: 
function DirectedCodeword(sigma::CodeWord)::DirectedCodeword

**Comment by sekunder** [comment]
1. What is the canonical sorting order for `sigma`? Julia does not guarantee that the elements of a `Set` are stored in any particular order.
2. Can you provide a short snippet of code demonstrating the problem?

**Comment by vitskov** [comment]
# This is I currently do to run around this problem:

function ConvertToDirectedCodeword(σ::Union{CodeWord,Set{Int8}})::DirectedCodeword
if isempty(σ) return EmptyDirectedCodeword
else return TheIntegerType.(sort(collect(σ)));
end
end

**Comment by vitskov** [comment]
.
