### ISSUE TITLE
still not fully compatible with Julia 1.0 

### ISSUE THREAD

**Issue by vitskov** [nebneuron/Simplicial#17]
the first obvious bug is the comments to some functions (same as in julia 0.7)

**Comment by vitskov** [comment]
Julia 1.0 introduced quite a number of breaking changes.  I expect Julia 1.0 to not work with a lot of major julia packages (e.g. JuMP) for quite some time.... I abstain from further comments on this issue.

A  large number of fixes has been made to Simplicial  as of the time of writing this note to fix various incompatibilities, while keeping the backwards compatibility with Julia 0.6 -- since this is the de facto latest julia version that does not break anything in most major packages... :-| .

I have tested only *some*  functionality. This means that a number of methods and constructors are still broken when working under Julia 1.0. Alex, do you want to take charge of the combinatorial side of things?

**Comment by sekunder** [comment]
I'm closing this in favor of having #14 as the open "compatibility" issue; see my comments there.
