### ISSUE TITLE
vertex type not stable when passing AbstractFiniteSetCollections to each other

### ISSUE THREAD

**Issue by sekunder** [nebneuron/Simplicial#20]
Vertex type should be preserved when constructing, e.g. a CombinatorialCode from a SimplicialComplex. Example below:

```
julia> K = SimplicialComplex([[1,2],[2,3],[1,3]], squash_int_type=false) # vertex type Int64
Simplicial.SimplicialComplex{Int64}
1-dimensional simplicial complex on 3 vertices with 3 facets
    V = {1, 2, 3}
max K = {1 2, 1 3, 2 3}


julia> C = CombinatorialCode(K) # vertex type not preserved
Simplicial.CombinatorialCode{Int8}
Code on [3] with 7 codewords
C = {emptyset, 1, 2, 3, 1 2, 1 3, 2 3}
```

**Comment by sekunder** [comment]
I believe my commit should fix the issue(s). @vitskov could you please checkout this branch and test your existing scripts, and report any errors you encounter?

**Comment by vitskov** [comment]
Hi Alex, 
What commit? What branch? 
V

**Comment by sekunder** [comment]
Branch: [gh-#20-vertex-type-stability](https://github.com/nebneuron/Simplicial.jl/tree/gh-%2320-vertex-type-stability)

Commit: [7d02cbf](https://github.com/nebneuron/Simplicial.jl/commit/7d02cbfb0cb5c75334c442e43ee1d8c611d35e08)

To be more detailed: Ostensibly something like the following should work (from terminal):
```
> cd ~/path/to/julia/v0.6/Simplicial
> git pull
> git checkout gh-#20-vertex-type-stability
```
Once that's done, start a new instance of julia and run any code which has `using Simplicial` somewhere in it.

**Comment by vitskov** [comment]
fixed
