### ISSUE TITLE
function show is broken in Julia 1

### ISSUE THREAD

**Issue by vitskov** [nebneuron/Simplicial#21]
################################################################################
################################################################################
### This function is broken in Julia 1 please fix!
# function show(io::IO, C::AbstractCombinatorialCode)
#    if !get(io, :compact, false)
#        println(io, typeof(C))
#    end
#    print(io, "Code on [$(maximum(vertices(C)))] with $(length(C)) codewords")
#    if !get(io, :compact, false)
#        println(io)
#        println(io, "C = {$(join(C, ", "))}")
#    end
# end

**Comment by sekunder** [comment]
This seems to have been a problem with iteration, since `join` uses the iteration interface. Pull request #28 should fix it, so I'm closing this issue.
