### ISSUE TITLE
CombinatorialCode of an empty collection of codewords produces an error 

### ISSUE THREAD

**Issue by vitskov** [nebneuron/Simplicial#22]
CombinatorialCode(Array{Set{Int8},1}())

ERROR: ArgumentError: collection must be non-empty
Stacktrace:
 [1] extrema(::Set{Any}) at ./reduce.jl:491
 [2] #CombinatorialCode#11(::Bool, ::Bool, ::Type{T} where T, ::Array{Set{Int8},1}, ::Set{Any}) at /Users/vladimiritskov/.julia/v0.6/Simplicial/src/CombinatorialCodes/CombinatorialCodes.jl:82
 [3] Simplicial.CombinatorialCode(::Array{Set{Int8},1}, ::Set{Any}) at /Users/vladimiritskov/.julia/v0.6/Simplicial/src/CombinatorialCodes/CombinatorialCodes.jl:81 (repeats 2 times)

**Comment by sekunder** [comment]
This should have been fixed along with vertex type stability in the fix for #20 . Please test that branch and if it is satisfactory merge it in to master, since it should fix this problem as well.

**Comment by vitskov** [comment]
Had you tested this yourself?
I am very rusty on merging, etc on github.
If this works as prescribed, can you please merge this yourself?


On Feb 4, 2019, at 1:51 PM, Alex Kunin <notifications@github.com<mailto:notifications@github.com>> wrote:


This should have been fixed along with vertex type stability in the fix for #20<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnebneuron%2FSimplicial.jl%2Fissues%2F20&data=02%7C01%7Cvui1%40psu.edu%7Cec0ff4ca4556467a7f2008d68ad1cfc8%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636849031067672322&sdata=gVHHFNJddvDbUXBNA9MnK1Ue0bA9Z3NTDh8qNX0RMdY%3D&reserved=0> . Please test that branch and if it is satisfactory merge it in to master, since it should fix this problem as well.

**Comment by sekunder** [comment]
In my experience, regardless of how much I test things, your use cases are so wildly different from mine that you inevitably discover bugs that are invisible to me. As such, I insist that you test it yourself. Instructions should be here: https://github.com/nebneuron/Simplicial.jl/issues/20#issuecomment-441404533

To merge it, go to this page: https://github.com/nebneuron/Simplicial.jl/branches and click "New pull request" next to "gh-#20-vertex-type-stability"

**Comment by vitskov** [comment]
nope, your update conflicts with 

https://github.com/nebneuron/Simplicial.jl/blob/master/src/CombinatorialCodes/examples_of_codes.jl

see the function CombinatorialCodeOnThreeNeurons there

 Can you please harmonize these to work together as desired, and then merge?

**Comment by vitskov** [comment]
fixed
