### ISSUE TITLE
fvector does not work 

### ISSUE THREAD

**Issue by vitskov** [nebneuron/Simplicial#32]
I believe this issue is closely related to the previous issue..

julia> K=SimplicialComplex(CodeWord.([ [1 , 2 ], [ 2, 3 ]]) )
SimplicialComplex{Int16}
  1-dimensional simplicial complex on 3 vertices with 2 facets
      V = {1, 2, 3}
  max K = {1 2, 2 3}

julia> fvector(K)
ERROR: UndefVarError: f not defined
Stacktrace:
 [1] iterate(::SimplicialComplex{Int16}) at /Users/vui1/.julia/packages/Simplicial/xBWw3/src/SimplicialComplexes/SimplicialComplex.jl:124
 [2] fvector(::SimplicialComplex{Int16}) at /Users/vui1/.julia/packages/Simplicial/xBWw3/src/SimplicialComplexes/SimplicialComplex.jl:48
 [3] top-level scope at REPL[17]:1

**Comment by vitskov** [comment]
this is the same issue. The label "the abstract collection disaster" is here for a reason

**Comment by sekunder** [comment]
Give it a test now, I believe I fixed the issue with commit 5ef454af42f6201467d2094e9dd38ee681625331

**Comment by vitskov** [comment]
Great!
Thank you.

**Comment by vitskov** [comment]
P.S. Note that the output of fvector of a d-dimensional complex has length (d+2). This is because the first element measures the number of (-1)-dimensional simplices (i.e. the single empty set). Perhaps the help for this function should carefully explain the output, so that there is no possible confusion...
