### ISSUE TITLE
Is this "the" package for p-FEM meshes?

### ISSUE THREAD

**Issue by dlfivefifty** [nebneuron/Simplicial#33]
In p-FEM one needs a way to work with not just (in 2D) triangular meshes, but also the full simplicial complex as the basis consist of "bubble functions", supported in a single element and zero on the boundary,  "face bubbles", which are defined by a basis on the interface between two adjacent elements, that vanishes at the grid points, and finally the standard first-order FEM basis defined by its value on the mesh.

Do you see this package as supporting this? I'm not entirely clear what operations are needed, but one would certainly need to be able to access the faces(?) of a simplex, and given a face be able to find all adjoining elements. This would be needed in both 2D and 3D.

Going beyond this I would also want other similar structures built from non-simplices, for example:

1. rectangular meshes (and their faces, etc.)
2. annular meshes (and their faces, which are circles in 2D or spheres in 3D)
3. exotically shaped elements

Am I right that since (2) is topologically(?) the same as a 1D mesh you would represent it that way, that is, the actual geometry of the meshes is not important, just how they are interconnected? This is fine. But I'm guessing 1 and 3 are harder since they aren't simplices.

**Comment by vitskov** [comment]
Hello, 


Package Simplicial is designed for doing computational topology, but not numerical methods. 

I suspect you are looking in the wrong place.  

Best,
Vladimir

**Comment by vitskov** [comment]
see my message above

**Comment by dlfivefifty** [comment]
I don’t think you read the comment. One needs to do computational topology in the construction of numerical methods. I’m not asking if you are doing the numerics here but rather if this package can do the topological aspects
